# Generated by Django 5.0.6 on 2024-06-23 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.TextField(max_length=128)),
                ('description', models.TextField(max_length=500)),
                ('price', models.IntegerField()),
                ('rooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('photo_main', models.ImageField(null=True, upload_to='media/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('posted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
