# Generated by Django 5.0.6 on 2024-06-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.AddField(
            model_name='listing',
            name='User',
            field=models.CharField(default='anonim', max_length=50),
        ),
    ]
